export enum ErrorCodes {
    INVALID_USER_ID = "USER-001",
    INVALID_USER_EMAIL = "USER-002",
    INVALID_USER_PASSWORD = "USER-003",
    INVALID_USER_DATA = "USER-004",
    USER_ALREADY_EXISTS = "USER-100",
    PROFILE_ALREADY_EXISTS = "PROF-100",
    USER_NOT_FOUND = "USER-901",
    USER_INTERNAL_ERROR = "USER-900",
    PROFILE_INTERNAL_ERROR = "PROF-900",
    INVALID_PROFILE_ID = "PROF-001",
    PROFILE_NOT_FOUND = "PROF-901",
}